#!/bin/sh

cd ../..

for opts in \
	"--host-system=Linux" \
	"--host-system=NetBSD" \
	"--host-system=FreeBSD" \
	"--without-nettle" \
	"--without-nettle --without-nss" \
	"--without-nettle --without-nss --without-tomcrypt" \
	"--without-nettle --without-nss --without-tomcrypt --without-gnutls"
do
	./configure $opts
	scan-build make "$@" || exit 1
done
