#!/bin/sh

LANG=C
export LANG

if [ $# -ne 1 ]; then
  echo "Usage : $0 <version>"
  exit 2
fi

version=$1
tag=$version
subdir=chrony-${version}
mandate=$(date +'%B %Y')

umask 022

if [ ! -d .git ]; then
  echo "No .git subdirectory?"
  exit 3
fi

[ -d RELEASES ] || mkdir RELEASES

rm -rf RELEASES/$subdir

if [ $version != test ]; then
  git tag -s $tag || exit 1
else
  tag=HEAD
fi

git archive --format=tar --prefix=RELEASES/${subdir}/ $tag | \
  tar xf - || exit 1

cd RELEASES/$subdir || exit 1

echo $version > version.txt

sed -e "s%@@VERSION@@%${version}%" < chrony.spec.sample > chrony.spec

for m in chrony.1 chronyc.1.in chrony.conf.5.in chronyd.8.in; do
  sed -e "s%@VERSION@%${version}%;s%@MAN_DATE@%${mandate}%" \
    < $m > ${m}_
  mv -f ${m}_ $m
done

./configure && make chrony.txt || exit 1
mv chrony.txt chrony.txt_
make distclean
mv chrony.txt_ chrony.txt

rm -f config.h config.log faqgen.pl make_release chrony.spec.sample .gitignore

cd ..
tar cv --owner root --group root $subdir | gzip -9 > ${subdir}.tar.gz

[ $version != test ] && \
  gpg -b -a -o ${subdir}-tar-gz-asc.txt ${subdir}.tar.gz
