#!/bin/bash

. test.common
test_start "initstepslew directive"

freq_offset=0.0
wander=0.0
limit=100

# clknetsim requires source port (if bound) to match dest port
client_server_options="port 124"
client_conf="initstepslew 5 192.168.123.1
port 124"

min_sync_time=15
max_sync_time=30

for time_offset in -2.0 -0.2 0.2 2.0; do
	run_test || test_fail
	check_chronyd_exit || test_fail
	check_sync || test_fail
done

min_sync_time=1
max_sync_time=1

for time_offset in -1e8 -1e2 1e2 1e8; do
	run_test || test_fail
	check_sync || test_fail
done

test_pass
